title: Go2GirlSquared Coding Journey
author: Niquewill
email: go2girlsquared@gmail.com
description: > # this means to ignore newlines until "baseurl:"
This is the journey of a coder.  I will use quotes that will inspire and motivate me.  I promise to be honest, open, and vulnerable to the process of learning in hopes of encouraging others to start and reflect once I arrive to my destination.

# social links
twitter_username: @Go2GirlSquared
github_username:  Niquewill
Instagram: Go2GirlSqrd

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-leap-day
